server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234



  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 579246999082-g4817qa0svom0jsk9b47p16j4pibsgom.apps.googleusercontent.com
            client-secret: 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
            scope: # Scope 설정 (어느 범위까지 받아올건지)
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          facebook:
            client-id: 437949511596732
            client-secret: 8f6788b5779aabb17358c0e5c0369c86
            scope:
              - email
              - public_profile
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook
          naver:
            client-id: FNuHkkM6wMXwxnsr3PPb
            client-secret: _34iq7OQiW
            scope:
              - email
              - public_profile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider: # provider 가 등록이 되어있지 않기 때문에 이렇게 따로 설정해주어야함
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 인증창 접근
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰 발급
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보 조회
            user-name-attribute: response # 회원정보를 json 으로 받는데 response 라는 키 값으로 네이버가 리턴


